services:
  - type: web
    name: bluestock-ipo-webapp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn IPO.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bluestock-db
          property: connectionString
    autoDeploy: true


    preDeployCommand: python manage.py migrate
