# Generated by Django 5.2.4 on 2025-07-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('open_date', models.DateField()),
                ('close_date', models.DateField()),
                ('price_band', models.CharField(max_length=100)),
                ('listing_date', models.DateField()),
                ('logo', models.ImageField(upload_to='logos/')),
                ('rhp_drhp', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
